[package]
name = "wallet"
version = "1.0.0-beta.1"
edition = "2021"

[dependencies]
secp256k1 = { workspace = true }
bip39 = "2.2.0"

ripemd = { workspace = true }
sha2 = { workspace = true }

zcash_primitives = { workspace = true } # version = "0.26.1"
zcash_client_backend = { path = "../../librustzcash/zcash_client_backend", features = ["lightwalletd-tonic"] } # version = "0.21.0"
zcash_client_memory = { path = "../../librustzcash/zcash_client_memory", features = ["orchard", "transparent-inputs"] }
zcash_client_sqlite = { path = "../../librustzcash/zcash_client_sqlite", features = ["orchard", "transparent-inputs"] } # version = "0.19.0"
zcash_keys = { workspace = true, features=["transparent-inputs"] }
zcash_protocol = { workspace = true } # version = "0.7.1"
zcash_transparent = { workspace = true } # version = "0.6.1"
zcash_note_encryption = { workspace = true } # version = "0.4.1"
zcash_proofs = { workspace = true, features = ["bundled-prover"] }
zcash_script = { workspace = true }

zip32 = { workspace = true }

rand = { version = "0.8", default-features = false }
rand_core = { version = "0.6", default-features = false }
rand_distr = { version = "0.4", default-features = false }
rand_chacha = "0.3.1"

rusqlite = { version = "0.37", features = ["bundled"] }

prost = "0.14.1"
byteorder = { workspace = true }
tonic = { workspace = true, features = ["transport", "channel", "tls-ring", "tls-webpki-roots"] }
tonic-build = { workspace = true, default-features = false }
rustls = { version = "0.23.31", default-features = false, features = ["ring"] }
tokio = { workspace = true, features = ["time", "rt-multi-thread", "macros", "tracing", "signal"] }
tokio-rustls = { version = "0.26", default-features = false }
tokio-stream = { workspace = true, features = ["time"] }
reqwest = { version = "0.12", default-features = false, features = ["cookies", "rustls-tls"] }

secrecy = "0.8.0"
sapling-crypto = "0.5.0"
orchard = "0.11.0"
incrementalmerkletree.workspace = true
shardtree.workspace = true
